# docker-compose.yml

version: '3'
services:
   webtester:
        build: 
            context: .
            dockerfile: seldnet.docker
        #image: wti:latest
        container_name: webtester
        entrypoint: "dotnet run"
        ports: 
            - 5000:80
        expose:
            - 80
        volumes: 
            - ./:/webtester